install.packages('tidyverse')
install.packages('tidymodels')
install.packages('tidytext')
# install.packages('scales')
# install.packages('sf')
# install.packages('sp')
# install.packages('gstat')
# install.packages('rgdal')
install.packages('glmnet')
# install.packages('rpart')
# install.packages('randomForest')
# install.packages('gbm')
# install.packages('splines')
# install.packages('RSNNS')
# install.packages('keras')
# install.packages('reticulate')
# install.packages('tensorflow')
install.packages('textstem')
# install.packages('nnet')
install.packages('qdapRegex')
install.packages('rvest')
install.packages('tokenizers')
install.packages('stopwords')
install.packages('sparsesvd')
install.packages('Matrix')
