---
title: "Learning outcomes"
editor: visual
---

This course emphasizes collaborative, interactive, and hands-on learning. Instruction in PSTAT197A will support all students in:

-   using modern technology and version control to collaborate efficiently on programming for data science projects;

-   recognizing and articulating problem patterns based on data semantics and one or more research questions;

-   identifying and accessing resources to aid in learning independently about methodology and/or application domains pertinent to a problem of interest;

-   communicating data analysis and/or research findings in a project team setting and to a small audience of peers.

Course staff are committed to creating an inclusive learning environment. Data science involves a combination of computing, statistics and probability, and domain expertise, as well as use of technology and narrative communication and storytelling, and no one person should expect to be an expert in all of these areas. Course staff recognize this fact that core competencies vary considerably, acknowledge that each student has particular strengths and weaknesses and interests, and make their best effort to avoid promoting one skill set over others in the practice of data science.
