---
title: "Course schedule"
editor: visual
---

This schedule is tentative and may be adjusted at the discretion of the instructor. Check back for updates.

+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| Week       | Theme                      | Monday meeting                                    | Wednesday meeting                               | Section meeting                  |
+============+============================+===================================================+=================================================+==================================+
| 0          | Module 0: Introductions    | NO CLASS                                          | Course orientation                              | NO LAB                           |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 1          | Module 0: Introductions    | 0.1 Lecture:                                      | 0.2 Activity:                                   | Software and technology overview |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   on research projects in(volving) data science | -   collaboration using GitHub                  |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 2          | Module 0: Introductions    | 0.3 Lecture/discussion:                           | 0.4 Activity:                                   | tidyverse                        |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   introducing class survey data                 | -   exploratory and descriptive analysis        |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 3          | Module 1: biomarkers       | 1.1 Discussion/lecture:                           | 1.2 Lecture:                                    | tidymodels                       |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   sharing results of survey data analysis;      | -   on prediction                               |                                  |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   introducing biomarker data                    |                                                 |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 4          | Module 1: biomarkers       | 1.3 Lecture:                                      | 1.4 Lecture/discussion:                         | classification                   |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   on classification                             | -   on variable selection;                      |                                  |
|            |                            |                                                   |                                                 |                                  |
|            |                            |                                                   | -   review published analysis of biomarker data |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 5          | Module 2: web fraud        | 2.1 Lecture/discussion:                           | 2.2 Lecture:                                    | text processing                  |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   sharing analysis of soil temperature data;    | -   on text as data                             |                                  |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   introducing web fraud data                    |                                                 |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 6          | Module 2: web fraud        | 2.3 Lecture:                                      | 2.4 Activity:                                   | keras                            |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   on multiclass classification                  | -   measuring classification accuracy           |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 7          | Module 3: soil temperature | 3.1 Discussion/lecture:                           | 3.2 Lecture:                                    | time series analysis             |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   sharing results of biomarker analysis;        | -   on time                                     |                                  |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   introducing soil temperature data             |                                                 |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 8          | Module 3: soil temperature | 3.3 Lecture:                                      | 3.4 Discussion: results                         | spatial analysis                 |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   on space                                      |                                                 |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 9          | Module 4: vignettes        | 4.1 Activity:                                     | NO CLASS                                        | NO LAB                           |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   workshopping vignettes                        |                                                 |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+
| 10         | Module 4: vignettes        | 4.2 Activity:                                     | 4.3 Activity/discussion:                        | NO LAB                           |
|            |                            |                                                   |                                                 |                                  |
|            |                            | -   teaching exchange                             | -   teaching exchange;                          |                                  |
|            |                            |                                                   |                                                 |                                  |
|            |                            |                                                   | -   closing                                     |                                  |
+------------+----------------------------+---------------------------------------------------+-------------------------------------------------+----------------------------------+

### 
