---
title: "Technology"
editor: visual
---

## Software {#sec-software}

Computing in PSTAT197A will be shown in R, and codes and other materials will be shared via GitHub. The following software will be required to access course materials:

-   [R](https://www.r-project.org/)

-   [RStudio](https://www.rstudio.com/products/rstudio/download/) 

-   [Git](https://git-scm.com/downloads)

-   [GitHub Desktop](https://desktop.github.com/) (or another visual GitHub client)

Installations and basic functionality will be covered in the first section meeting.

While PSTAT197A is not language-agnostic and some instruction in R is provided, it is also not a course especially emphasizing programming technique in R. Students are free to use or experiment with other software at their discretion provided it does not interfere with their participation in the class, but are expected to submit work and collaborate using RStudio-supported files.

## GitHub {#sec-github}

Students will learn and practice basic functionality of Git and GitHub for version control and collaboration by accessing course materials via GitHub repositories and submitting work via repository contributions.

We have a GitHub classroom for the data science capstone. Materials will be deployed via direct links. Students will be asked to submit work by contributing to team repositories; any such contributions will remain visible to course staff and team contributors, and so are not strictly private.

To access GitHub Classroom materials students will need to create a GitHub account if they do not already have one. Here is some [advice on choosing a username](https://happygitwithr.com/github-acct.html#username-advice).
